### ISSUE TITLE
Recent error showing up

### ISSUE THREAD

**Issue by psyciknz** [x86dev/docker-ttrss#57]
Has anyone seen this pop up?  It just started appearing in the last 24 hours.
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 7 no connection to the server in /var/www/ttrss/classes/db/migrations.php:87

Stack trace:
#0 /var/www/ttrss/classes/db/migrations.php(87): PDO->query()
#1 /var/www/ttrss/classes/db/migrations.php(80): Db_Migrations->create_migrations_table()
#2 /var/www/ttrss/classes/config.php(398): Db_Migrations->get_version()
#3 /var/www/ttrss/classes/logger/sql.php(15): Config::get_schema_version()
#4 /var/www/ttrss/classes/logger.php(39): Logger_SQL->log_error()
#5 /var/www/ttrss/classes/logger.php(32): Logger->_log_error()
#6 /var/www/ttrss/include/errorhandler.php(81): Logger::log_error()
#7 [internal function]: ttrss_fatal_handler()

```

I haven't yet gone down the "official docker-compose" route yet, in the hope someone using this contain has had this occur.
Version: [Tiny Tiny RSS](https://tt-rss.org/) v22.04-b17b4a4 (Unsupported) © 2005-2022 [Andrew Dolgov](https://fakecake.org/)

**Comment by x86dev** [comment]
Sorry no, latest versions work fine for me here.
